-- Script para adicionar as novas colunas na tabela SAT_CfeItem
-- Execute este script no SQL Server para atualizar a estrutura da tabela

-- Alterar origem_mercadoria de INT para VARCHAR(100)
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'origem_mercadoria')
BEGIN
    ALTER TABLE SAT_CfeItem ALTER COLUMN origem_mercadoria VARCHAR(100) NULL;
END

-- Alterar tributacao_icms de VARCHAR(10) para VARCHAR(100)
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'tributacao_icms')
BEGIN
    ALTER TABLE SAT_CfeItem ALTER COLUMN tributacao_icms VARCHAR(100) NULL;
END

-- Adicionar novos campos se não existirem
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'info_adicional')
    ALTER TABLE SAT_CfeItem ADD info_adicional TEXT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'regra_calculo')
    ALTER TABLE SAT_CfeItem ADD regra_calculo VARCHAR(10) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'outras_despesas')
    ALTER TABLE SAT_CfeItem ADD outras_despesas DECIMAL(12, 2) DEFAULT 0.00;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'rateio_desconto')
    ALTER TABLE SAT_CfeItem ADD rateio_desconto DECIMAL(12, 2) DEFAULT 0.00;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'rateio_acrescimo')
    ALTER TABLE SAT_CfeItem ADD rateio_acrescimo DECIMAL(12, 2) DEFAULT 0.00;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'aliquota_efetiva')
    ALTER TABLE SAT_CfeItem ADD aliquota_efetiva DECIMAL(8, 4) DEFAULT 0.00;

-- PIS
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'pis_cst')
    ALTER TABLE SAT_CfeItem ADD pis_cst VARCHAR(100) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'pis_base_calculo')
    ALTER TABLE SAT_CfeItem ADD pis_base_calculo DECIMAL(12, 2) DEFAULT 0.00;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'pis_aliquota')
    ALTER TABLE SAT_CfeItem ADD pis_aliquota DECIMAL(8, 4) DEFAULT 0.00;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'pis_valor')
    ALTER TABLE SAT_CfeItem ADD pis_valor DECIMAL(12, 2) DEFAULT 0.00;

-- COFINS
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'cofins_cst')
    ALTER TABLE SAT_CfeItem ADD cofins_cst VARCHAR(100) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'cofins_base_calculo')
    ALTER TABLE SAT_CfeItem ADD cofins_base_calculo DECIMAL(12, 2) DEFAULT 0.00;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'cofins_aliquota')
    ALTER TABLE SAT_CfeItem ADD cofins_aliquota DECIMAL(8, 4) DEFAULT 0.00;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'cofins_valor')
    ALTER TABLE SAT_CfeItem ADD cofins_valor DECIMAL(12, 2) DEFAULT 0.00;

-- Tributos aproximados
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SAT_CfeItem' AND COLUMN_NAME = 'valor_aproximado_tributos')
    ALTER TABLE SAT_CfeItem ADD valor_aproximado_tributos DECIMAL(12, 2) DEFAULT 0.00;

PRINT 'Migração concluída com sucesso!';
